"""Phase 16.5A6 — Enterprise Data Backfill Engine.

Populates the Enterprise Configuration layer from the legacy ConversationState
string columns, per the approved Phase 16.5A6-P Runbook
(`docs/09_MIGRATIONS/PHASE_16_5A6_ENTERPRISE_BACKFILL_RUNBOOK.md`).

Governance — both binding, both enforced structurally in this module:

  ADR-018 (Business Conversion Independence)
      `is_admitted` is an independent, staff-owned business fact and is NEVER
      derived from the pipeline. This module MUST NOT read or write
      `is_admitted`, and MUST NOT read `stage_category`, when linking. It reads
      `is_admitted` in exactly one place — the Step 7 parity audit — where it is
      compared and never assigned.

  ADR-019 (Compatibility Pipeline Standard)
      Stage `internal_key` values are the exact legacy router strings, verbatim.
      `Offering.name` stores the exact legacy `course` string; dedup is on the
      exact `(tenant_id, name)` pair — never a slug, never case-folded.

The Fail-Safe Property (Runbook §1)
    The 16.5A5-I adapters are gated on `pipeline_stage_id`. A row left with
    `pipeline_stage_id = NULL` reads its legacy column and is therefore correct.
    There is no partially-broken state: a row is either migrated-and-verified or
    untouched-and-correct. Consequently, when in doubt this engine SKIPS. Every
    "unlinkable" condition resolves to "leave NULL", which is a safe outcome and
    not a failure.

The engine is idempotent, restartable, tenant-scoped and single-threaded.
Running it ten times produces exactly the same database as running it once.
"""

import logging
import re
from datetime import datetime

from app.extensions import db
from app.models import (
    ConversationOffering,
    ConversationState,
    Offering,
    PipelineDefinition,
    PipelineStage,
)

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════════════
# Locked design parameters — Runbook §3. NOT tunable at the call site.
# Changing any value here is an architectural decision requiring an ADR.
# ══════════════════════════════════════════════════════════════════════════

COMPAT_PIPELINE_KEY = "legacy_compat"
COMPAT_PIPELINE_NAME = "Legacy Compatibility Pipeline"
COMPAT_PIPELINE_DESC = (
    "Auto-generated by Phase 16.5A6. Preserves legacy router stage vocabulary "
    "(ADR-019). Do not rename stage internal_keys."
)

BATCH_SIZE = 500
MAX_SLUG_ATTEMPTS = 100

# Frozen internal_key regex. Runbook §3.3: never relax without an ADR.
INTERNAL_KEY_RE = re.compile(r"^[a-z0-9_]+$")

# Runbook §3.2 — the canonical 12.
#   internal_key is the EXACT legacy router string (ADR-019) — never rename.
#   stage_category: only `enrolled` is 'won'; everything else 'open'. Deliberately
#   conservative — `done`/`not_sure` are NOT 'lost' because 'lost' may later drive
#   campaign suppression, which would be a behaviour change. Per ADR-018 the
#   category is informational and cannot affect `is_admitted`.
# (internal_key, display_name, stage_category, order_index, is_entry, is_terminal)
CANONICAL_STAGES = (
    ("new",                   "New",                   "open", 0,  True,  False),
    ("goal_selection",        "Goal Selection",        "open", 1,  False, False),
    ("course_recommendation", "Course Recommendation", "open", 2,  False, False),
    ("course_viewed",         "Course Viewed",         "open", 3,  False, False),
    ("demo_time_ask",         "Demo Time Requested",   "open", 4,  False, False),
    ("demo_date_ask",         "Demo Date Requested",   "open", 5,  False, False),
    ("demo_booked",           "Demo Booked",           "open", 6,  False, False),
    ("offer_menu",            "Offer Menu",            "open", 7,  False, False),
    ("payment_pending",       "Payment Pending",       "open", 8,  False, False),
    ("enrolled",              "Enrolled",              "won",  9,  False, True),
    ("not_sure",              "Not Sure",              "open", 10, False, False),
    ("done",                  "Done",                  "open", 11, False, True),
)

CANONICAL_KEYS = frozenset(s[0] for s in CANONICAL_STAGES)

# Legacy attributes mirrored into custom_attributes (Step 6). Mirrors the
# 16.5A5-I `offer_course` / `batch_time` adapters, which read JSON-first.
JSON_MIRROR_ATTRS = ("offer_course", "batch_time")


def slugify(value):
    """Derive an `internal_key` from a name — Runbook §3.4.

    NEVER applied to `Offering.name`, which must stay byte-identical to the
    legacy course string (ADR-019). This produces the machine key only.
    """
    t = value.lower()
    t = re.sub(r"[^a-z0-9]+", "_", t)
    t = t.strip("_")[:50].rstrip("_")
    return t or "offering"


class BackfillAbort(Exception):
    """Aborts the current tenant. Already-committed batches stay valid and
    correct (fail-safe property), so this never leaves torn state."""


class TenantReport:
    """Per-tenant audit counters — Runbook §4 'Audit' rows."""

    def __init__(self, tenant_id):
        self.tenant_id = tenant_id
        # Step 1
        self.pipelines_created = 0
        self.pipelines_reused = 0
        # Step 2
        self.stages_created = 0
        self.stages_reused = 0
        self.extra_stages_seeded = 0
        self.unlinkable_stage_values = []
        # Step 3
        self.offerings_created = 0
        self.offerings_reused = 0
        self.slug_collisions_resolved = 0
        # Step 4
        self.bridges_created = 0
        self.bridges_skipped = 0
        # Step 5
        self.rows_linked = 0
        self.rows_skipped_already = 0
        self.rows_unlinkable = 0
        # Step 6
        self.attrs_enriched = 0
        self.attrs_preserved = 0
        # Step 7
        self.rows_verified = 0
        self.mismatches = []
        self.concurrent_writes = []
        # timing
        self.batches = 0
        self.duration_s = 0.0

    def as_dict(self):
        return {k: v for k, v in self.__dict__.items()}


class BackfillEngine:
    """Executes Runbook Steps 1-7 for every active tenant.

    Args:
        dry_run: when True, computes the complete plan and writes nothing.
                 Every would-be write is counted instead of executed.
    """

    def __init__(self, dry_run=True, batch_size=BATCH_SIZE):
        self.dry_run = dry_run
        self.batch_size = batch_size
        self.reports = []

    # ── entry point ─────────────────────────────────────────────────────
    def run(self):
        mode = "DRY RUN" if self.dry_run else "LIVE"
        logger.info("Phase 16.5A6 backfill starting (%s)", mode)
        for tenant_id in self._active_tenants():
            report = TenantReport(tenant_id)
            started = datetime.utcnow()
            try:
                self._run_tenant(tenant_id, report)
            except BackfillAbort as exc:
                logger.error("tenant=%s ABORTED: %s", tenant_id, exc)
                if not self.dry_run:
                    db.session.rollback()
            report.duration_s = (datetime.utcnow() - started).total_seconds()
            self.reports.append(report)
        return self.reports

    def _active_tenants(self):
        """Tenants with >=1 lead — Runbook §3.1 scope."""
        rows = (db.session.query(ConversationState.tenant_id)
                .distinct()
                .order_by(ConversationState.tenant_id)
                .all())
        return [r[0] for r in rows]

    def _run_tenant(self, tenant_id, report):
        logger.info("tenant=%s starting", tenant_id)

        # Runbook §Step 7 requires a legacy snapshot captured BEFORE Step 5.
        snapshot = self._snapshot_legacy(tenant_id)

        pipeline_id = self._step1_pipeline(tenant_id, report)
        stage_map = self._step2_stages(tenant_id, pipeline_id, report)
        offering_map = self._step3_offerings(tenant_id, report)
        self._step4_bridges(tenant_id, offering_map, report)
        self._step5_links(tenant_id, stage_map, report)
        self._step6_attrs(tenant_id, report)
        self._step7_verify(tenant_id, snapshot, report)

        logger.info("tenant=%s complete", tenant_id)

    # ── snapshot (Step 7 input) ─────────────────────────────────────────
    def _snapshot_legacy(self, tenant_id):
        """Raw legacy column values keyed by lead id, captured before Step 5.

        Reads the underscore-prefixed physical columns directly, bypassing the
        adapters, so the snapshot is unambiguous regardless of link state.
        `is_admitted` is read here for comparison only — never assigned (ADR-018).
        """
        rows = (db.session.query(
                    ConversationState.id,
                    ConversationState._stage,
                    ConversationState._course,
                    ConversationState._offer_course,
                    ConversationState._batch_time,
                    ConversationState.is_admitted,
                )
                .filter(ConversationState.tenant_id == tenant_id)
                .all())
        return {
            r[0]: {
                "stage": r[1], "course": r[2], "offer_course": r[3],
                "batch_time": r[4], "is_admitted": r[5],
            }
            for r in rows
        }

    # ── Step 1 — Compatibility Pipeline ─────────────────────────────────
    def _step1_pipeline(self, tenant_id, report):
        existing = (PipelineDefinition.query
                    .filter_by(tenant_id=tenant_id, internal_key=COMPAT_PIPELINE_KEY)
                    .first())
        if existing is not None:
            report.pipelines_reused += 1
            return existing.id

        # is_default only if the tenant has no existing default (Runbook §3.1 / F9).
        has_default = (PipelineDefinition.query
                       .filter_by(tenant_id=tenant_id, is_default=True)
                       .first()) is not None

        report.pipelines_created += 1
        if self.dry_run:
            return None

        pipeline = PipelineDefinition(
            tenant_id=tenant_id,
            internal_key=COMPAT_PIPELINE_KEY,
            name=COMPAT_PIPELINE_NAME,
            description=COMPAT_PIPELINE_DESC,
            is_default=not has_default,
            is_active=True,
        )
        db.session.add(pipeline)
        db.session.commit()
        return pipeline.id

    # ── Step 2 — Compatibility Stages ───────────────────────────────────
    def _step2_stages(self, tenant_id, pipeline_id, report):
        """Seed the canonical 12 + regex-valid extras. Returns {internal_key: id}.

        In dry-run pipeline_id is None, so the map holds sentinel Nones and is
        used only for membership tests by Step 5.
        """
        existing = {}
        if pipeline_id is not None:
            existing = {
                s.internal_key: s.id
                for s in PipelineStage.query.filter_by(pipeline_id=pipeline_id).all()
            }

        stage_map = dict(existing)

        # Canonical 12 — internal_key verbatim (ADR-019).
        for key, display, category, order, entry, terminal in CANONICAL_STAGES:
            if key in existing:
                report.stages_reused += 1
                continue
            report.stages_created += 1
            if self.dry_run:
                stage_map[key] = None
                continue
            stage = PipelineStage(
                pipeline_id=pipeline_id, internal_key=key, display_name=display,
                stage_category=category, order_index=order,
                is_entry=entry, is_terminal=terminal, is_active=True,
            )
            db.session.add(stage)
            db.session.flush()
            stage_map[key] = stage.id

        # Extras — distinct production stage values outside the canonical 12.
        extras = self._distinct_stages(tenant_id) - CANONICAL_KEYS
        for n, value in enumerate(sorted(extras)):
            if not INTERNAL_KEY_RE.match(value):
                # Runbook §3.3: do not seed, do not link. Rows stay NULL and
                # therefore read correctly via the legacy fallback.
                report.unlinkable_stage_values.append(value)
                continue
            if value in stage_map:
                report.stages_reused += 1
                continue
            report.stages_created += 1
            report.extra_stages_seeded += 1
            if self.dry_run:
                stage_map[value] = None
                continue
            stage = PipelineStage(
                pipeline_id=pipeline_id, internal_key=value, display_name=value,
                stage_category="open", order_index=100 + n,
                is_entry=False, is_terminal=False, is_active=True,
            )
            db.session.add(stage)
            db.session.flush()
            stage_map[value] = stage.id

        if not self.dry_run:
            db.session.commit()
        return stage_map

    def _distinct_stages(self, tenant_id):
        rows = (db.session.query(ConversationState._stage)
                .filter(ConversationState.tenant_id == tenant_id)
                .distinct()
                .all())
        return {r[0] for r in rows if r[0] not in (None, "")}

    # ── Step 3 — Offerings ──────────────────────────────────────────────
    def _step3_offerings(self, tenant_id, report):
        """One Offering per distinct EXACT course string. Returns {name: id}.

        ADR-019: `name` is stored verbatim and dedup is on the exact
        `(tenant_id, name)` pair. The slug feeds `internal_key` only.
        """
        existing = {
            o.name: o.id
            for o in Offering.query.filter_by(tenant_id=tenant_id).all()
        }
        used_keys = {
            o.internal_key
            for o in Offering.query.filter_by(tenant_id=tenant_id).all()
        }
        offering_map = dict(existing)

        for course in sorted(self._distinct_courses(tenant_id)):
            if course in existing:                 # exact-name dedup (ADR-019)
                report.offerings_reused += 1
                continue

            internal_key = self._unique_key(slugify(course), used_keys, report,
                                            tenant_id)
            used_keys.add(internal_key)
            report.offerings_created += 1
            if self.dry_run:
                offering_map[course] = None
                continue

            offering = Offering(
                tenant_id=tenant_id,
                internal_key=internal_key,
                name=course,                       # EXACT legacy string — ADR-019
                is_active=True,
                price=None,
                custom_attributes=None,
            )
            db.session.add(offering)
            db.session.flush()
            offering_map[course] = offering.id

        if not self.dry_run:
            db.session.commit()
        return offering_map

    def _unique_key(self, base, used_keys, report, tenant_id):
        """Resolve internal_key collisions with a numeric suffix — Runbook §3.4."""
        if base not in used_keys:
            return base
        for n in range(2, MAX_SLUG_ATTEMPTS + 2):
            suffix = f"_{n}"
            candidate = base[: 50 - len(suffix)] + suffix
            if candidate not in used_keys:
                report.slug_collisions_resolved += 1
                return candidate
        raise BackfillAbort(
            f"tenant={tenant_id}: slug collision unresolved after "
            f"{MAX_SLUG_ATTEMPTS} attempts for base={base!r} (F2)"
        )

    def _distinct_courses(self, tenant_id):
        rows = (db.session.query(ConversationState._course)
                .filter(ConversationState.tenant_id == tenant_id)
                .distinct()
                .all())
        return {r[0] for r in rows if r[0] not in (None, "")}

    # ── Step 4 — ConversationOffering bridges ───────────────────────────
    def _step4_bridges(self, tenant_id, offering_map, report):
        for batch in self._iter_batches(tenant_id):
            ids = [r.id for r in batch]
            existing_pairs = self._existing_bridge_pairs(ids)   # one query, no N+1
            for lead in batch:
                course = lead._course
                if course in (None, ""):
                    continue
                offering_id = offering_map.get(course)
                if offering_id is None and not self.dry_run:
                    report.bridges_skipped += 1
                    continue
                if (lead.id, offering_id) in existing_pairs:
                    report.bridges_skipped += 1
                    continue
                report.bridges_created += 1
                if self.dry_run:
                    continue
                db.session.add(ConversationOffering(
                    conversation_state_id=lead.id, offering_id=offering_id))
            if not self.dry_run:
                db.session.commit()

    def _existing_bridge_pairs(self, lead_ids):
        if not lead_ids:
            return set()
        rows = (db.session.query(ConversationOffering.conversation_state_id,
                                 ConversationOffering.offering_id)
                .filter(ConversationOffering.conversation_state_id.in_(lead_ids))
                .all())
        return {(r[0], r[1]) for r in rows}

    # ── Step 5 — pipeline_stage_id mapping (the activating step) ────────
    def _step5_links(self, tenant_id, stage_map, report):
        """Link pipeline_stage_id from the legacy `stage` string ONLY.

        🚫 ADR-018: this method MUST NOT read or write `is_admitted`, and MUST
        NOT read `stage_category`. Verified by test and by code review gate B.
        """
        for batch in self._iter_batches(tenant_id):
            for lead in batch:
                if lead.pipeline_stage_id is not None:
                    report.rows_skipped_already += 1
                    continue

                stage = lead._stage
                if stage in (None, ""):
                    # Runbook §3.3 — linking '' to `new` would flip the read
                    # from '' to 'new'. Leave NULL: the fallback is correct.
                    report.rows_unlinkable += 1
                    continue

                if stage not in stage_map:
                    report.rows_unlinkable += 1
                    continue

                report.rows_linked += 1
                if self.dry_run:
                    continue
                lead.pipeline_stage_id = stage_map[stage]
            if not self.dry_run:
                db.session.commit()
            report.batches += 1

    # ── Step 6 — custom_attributes enrichment ───────────────────────────
    def _step6_attrs(self, tenant_id, report):
        """Mirror offer_course / batch_time into the JSON blob.

        MERGE ONLY. `custom_attributes` is NOT uniformly NULL — the 16.5A5-I
        setters have been writing live bot JSON since deploy. An existing key is
        always preserved, never overwritten.
        """
        for batch in self._iter_batches(tenant_id):
            for lead in batch:
                current = dict(lead.custom_attributes or {})
                merged = dict(current)
                for attr in JSON_MIRROR_ATTRS:
                    value = getattr(lead, f"_{attr}")
                    if value in (None, ""):
                        continue                     # write only non-empty values
                    if current.get(attr) not in (None, ""):
                        report.attrs_preserved += 1  # live bot write — keep it
                        continue
                    merged[attr] = value
                if merged == current:
                    continue
                report.attrs_enriched += 1
                if self.dry_run:
                    continue
                # Reassign: db.JSON is not Mutable, so in-place mutation of the
                # dict would not flag the attribute dirty and would silently
                # never persist.
                lead.custom_attributes = merged or None
            if not self.dry_run:
                db.session.commit()

    # ── Step 7 — parity verification ────────────────────────────────────
    def _step7_verify(self, tenant_id, snapshot, report):
        """Prove 100% parity: every adapter read must equal its legacy value.

        Two comparisons per row:
          adapter vs CURRENT legacy column — the real invariant. A mismatch here
            is a migration defect (F7) → halt and roll back.
          adapter vs pre-Step-5 SNAPSHOT — the Runbook's stated check. A mismatch
            here that still satisfies the invariant above is a concurrent bot
            write (F8), which the Runbook classifies as benign and needing no
            rollback. Reported separately, never counted as a defect.
        """
        db.session.expire_all()   # force re-read through the adapters
        for batch in self._iter_batches(tenant_id):
            for lead in batch:
                snap = snapshot.get(lead.id)
                if snap is None:
                    continue     # created after the snapshot — not in scope
                current_legacy = {
                    "stage": lead._stage,
                    "course": lead._course,
                    "offer_course": lead._offer_course,
                    "batch_time": lead._batch_time,
                    "is_admitted": lead.is_admitted,
                }
                adapter = {
                    "stage": lead.stage,
                    "course": lead.course,
                    "offer_course": lead.offer_course,
                    "batch_time": lead.batch_time,
                    "is_admitted": lead.is_admitted,   # compared, never assigned
                }
                for field in ("stage", "course", "offer_course", "batch_time",
                              "is_admitted"):
                    if adapter[field] != current_legacy[field]:
                        report.mismatches.append({
                            "id": lead.id, "field": field,
                            "adapter": adapter[field],
                            "legacy": current_legacy[field],
                            "snapshot": snap[field],
                        })
                    elif adapter[field] != snap[field]:
                        report.concurrent_writes.append({
                            "id": lead.id, "field": field,
                            "snapshot": snap[field], "now": adapter[field],
                        })
                report.rows_verified += 1

        if report.mismatches:
            raise BackfillAbort(
                f"tenant={tenant_id}: {len(report.mismatches)} parity mismatch(es) "
                f"(F7) — HALT and execute the Rollback Checklist"
            )

    # ── keyset pagination ───────────────────────────────────────────────
    def _iter_batches(self, tenant_id):
        """Yield batches of leads, keyset-paginated (`id > last_seen`).

        Never OFFSET: it drifts under concurrent inserts and degrades on deep
        pages. Every query is tenant-scoped.
        """
        last_seen = 0
        while True:
            batch = (ConversationState.query
                     .filter(ConversationState.tenant_id == tenant_id)
                     .filter(ConversationState.id > last_seen)
                     .order_by(ConversationState.id)
                     .limit(self.batch_size)
                     .all())
            if not batch:
                return
            yield batch
            last_seen = batch[-1].id
