"""Phase 11-D1 Opt-Out Safety

Revision ID: 002e57d59f03
Revises: 5d03593d42b4
Create Date: 2026-06-09 14:21:01.605626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002e57d59f03'
down_revision = '5d03593d42b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_opted_out', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_state', schema=None) as batch_op:
        batch_op.drop_column('is_opted_out')

    # ### end Alembic commands ###
