"""phase15c5_b_email_verified_at

Revision ID: 21aed923eafb
Revises: 5a4dedcee918
Create Date: 2026-07-11 13:13:38.324132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21aed923eafb'
down_revision = '5a4dedcee918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email_verified_at'), ['email_verified_at'], unique=False)
        
    # Phase 15C.5-C: Grandfather existing users
    op.execute(
        sa.text('''
            UPDATE users 
            SET email_verified_at = CURRENT_TIMESTAMP 
            WHERE email IS NOT NULL 
              AND tenant_id IS NOT NULL 
              AND email_verified_at IS NULL
        ''')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_verified_at'))
        batch_op.drop_column('email_verified_at')
        
    # Note: Grandfathered timestamps (email_verified_at) are intentionally 
    # non-recoverable after downgrade since the entire column is dropped.
    # ### end Alembic commands ###
