"""feat: Phase 16.5A3 enterprise configuration foundation

Revision ID: 258025fe9676
Revises: 21aed923eafb
Create Date: 2026-07-16 10:26:54.968484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258025fe9676'
down_revision = '21aed923eafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('internal_key', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_json', sa.Text(), nullable=False),
    sa.Column('estimated_count', sa.Integer(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audience_rules', schema=None) as batch_op:
        batch_op.create_index('idx_audience_rule_active', ['tenant_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('header_type', sa.String(length=20), nullable=True),
    sa.Column('provider_template_id', sa.String(length=200), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('button_config', sa.Text(), nullable=True),
    sa.Column('variables', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider_template_id', name='uq_msg_template_tenant_provider')
    )
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_index('idx_msg_template_channel', ['tenant_id', 'channel'], unique=False)
        batch_op.create_index('idx_msg_template_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pipeline_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('internal_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'internal_key', name='uq_pipeline_def_tenant_key')
    )
    with op.batch_alter_table('pipeline_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_definitions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tag_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('internal_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'internal_key', name='uq_tag_def_tenant_key')
    )
    with op.batch_alter_table('tag_definitions', schema=None) as batch_op:
        batch_op.create_index('idx_tag_def_category', ['tenant_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_definitions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('settings', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_settings_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('pipeline_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('internal_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('stage_category', sa.String(length=10), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_entry', sa.Boolean(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'internal_key', name='uq_pipeline_stage_pipeline_key')
    )
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.create_index('idx_pipeline_stage_active', ['pipeline_id', 'is_active'], unique=False)
        batch_op.create_index('idx_pipeline_stage_category', ['stage_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_stages_pipeline_id'), ['pipeline_id'], unique=False)

    # ──────────────────────────────────────────────────────────────────────────
    # NOTE: Alembic autogenerated index/constraint drift on existing tables
    # (conversation_state, tenants, users) has been REMOVED from this migration.
    #
    # These were artifacts of a SQLite local test DB representing indexes
    # differently from production PostgreSQL. On production PostgreSQL:
    #   - ix_conversation_state_phone already exists
    #   - ix_tenants_slug already exists as a unique index
    #   - ix_users_email already exists as a unique index
    #
    # Executing those operations would DROP then RECREATE live production indexes
    # unnecessarily. They are safe to omit — no data or schema changes result.
    # ──────────────────────────────────────────────────────────────────────────
    # ### end Alembic commands ###


def downgrade():
    # ### Phase 16.5A3 downgrade — reverses only the 6 new tables ###
    # Drop in reverse dependency order (pipeline_stages before pipeline_definitions).
    # Existing production tables (tenants, users, conversation_state) are NOT touched.

    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stages_pipeline_id'))
        batch_op.drop_index('idx_pipeline_stage_category')
        batch_op.drop_index('idx_pipeline_stage_active')

    op.drop_table('pipeline_stages')

    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_settings_tenant_id'))

    op.drop_table('tenant_settings')

    with op.batch_alter_table('tag_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_definitions_tenant_id'))
        batch_op.drop_index('idx_tag_def_category')

    op.drop_table('tag_definitions')

    with op.batch_alter_table('pipeline_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_definitions_tenant_id'))

    op.drop_table('pipeline_definitions')

    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_templates_tenant_id'))
        batch_op.drop_index('idx_msg_template_status')
        batch_op.drop_index('idx_msg_template_channel')

    op.drop_table('message_templates')

    with op.batch_alter_table('audience_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_rules_tenant_id'))
        batch_op.drop_index('idx_audience_rule_active')

    op.drop_table('audience_rules')
    # ### end Alembic commands ###
