"""crm schema expansion

Revision ID: 322eeddc7246
Revises: d269f81c1d24
Create Date: 2026-05-28 12:23:13.749191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '322eeddc7246'
down_revision = 'd269f81c1d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
    'created_at',
    sa.DateTime(),
    nullable=False,
    server_default=sa.text('CURRENT_TIMESTAMP')
))
        batch_op.add_column(sa.Column('lead_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('assigned_staff', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lead_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_admitted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_state', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('is_admitted')
        batch_op.drop_column('lead_score')
        batch_op.drop_column('assigned_staff')
        batch_op.drop_column('lead_status')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
