"""add provider agnostic billing columns

Revision ID: 5a4dedcee918
Revises: a3f1b2c4d5e6
Create Date: 2026-06-13 12:23:56.904596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4dedcee918'
down_revision = 'a3f1b2c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_invoice_id', sa.String(length=100), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hosted_invoice_url', sa.String(length=500), nullable=True),
    sa.Column('billing_period_start', sa.DateTime(), nullable=True),
    sa.Column('billing_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_invoice_id')
    )
    with op.batch_alter_table('billing_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_invoices_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('billing_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_subscription_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_period_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('past_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('billing_exempt', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default=sa.text("'USD'")))
        batch_op.create_unique_constraint(None, ['billing_subscription_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('currency')
        batch_op.drop_column('billing_exempt')
        batch_op.drop_column('past_due_at')
        batch_op.drop_column('current_period_end')
        batch_op.drop_column('billing_subscription_status')
        batch_op.drop_column('billing_subscription_id')
        batch_op.drop_column('billing_customer_id')
        batch_op.drop_column('billing_provider')

    with op.batch_alter_table('billing_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_invoices_tenant_id'))

    op.drop_table('billing_invoices')
    # ### end Alembic commands ###
