"""Phase11 D3B2

Revision ID: 623e5fa136ef
Revises: 002e57d59f03
Create Date: 2026-06-09 16:13:27.579727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623e5fa136ef'
down_revision = '002e57d59f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_messages_phone'), ['phone'], unique=False)

    with op.batch_alter_table('follow_up_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_jobs', schema=None) as batch_op:
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('last_attempt_at')
        batch_op.drop_column('retry_count')

    with op.batch_alter_table('pending_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_messages_phone'))

    op.drop_table('pending_messages')
    # ### end Alembic commands ###
