"""initial postgres state

Revision ID: d269f81c1d24
Revises: 
Create Date: 2026-05-26 17:20:27.338288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd269f81c1d24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('course', sa.String(length=200), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('batch_time', sa.String(length=100), nullable=True),
    sa.Column('offer_course', sa.String(length=50), nullable=True),
    sa.Column('last_msg', sa.String(length=50), nullable=True),
    sa.Column('last_text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_state_phone'), ['phone'], unique=True)

    op.create_table('follow_up_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_up_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_up_jobs_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_up_jobs_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_jobs_phone'))
        batch_op.drop_index(batch_op.f('ix_follow_up_jobs_done'))

    op.drop_table('follow_up_jobs')
    with op.batch_alter_table('conversation_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_state_phone'))

    op.drop_table('conversation_state')
    # ### end Alembic commands ###
