"""Phase 4D message logging

Revision ID: d3c2ce4aa446
Revises: 322eeddc7246
Create Date: 2026-05-28 13:01:42.087067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c2ce4aa446'
down_revision = '322eeddc7246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.create_index('idx_msg_phone_created', ['phone', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_log_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_log_phone'))
        batch_op.drop_index('idx_msg_phone_created')

    op.drop_table('message_log')
    # ### end Alembic commands ###
